""" Added playlist_description column

Revision ID: 20c626e20684
Revises: 44a7cb99ec39
Create Date: 2023-09-11 14:51:51.573444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c626e20684'
down_revision = '44a7cb99ec39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playlist_description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_column('playlist_description')

    # ### end Alembic commands ###
