"""Making song_id on songs table nullable

Revision ID: 52759db3905c
Revises: 4161c41c696f
Create Date: 2023-09-07 22:32:04.284079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52759db3905c'
down_revision = '4161c41c696f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.alter_column('song_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.alter_column('song_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
