"""Added owner column to albums

Revision ID: fe69470c54e0
Revises: 9e6105d3a34a
Create Date: 2023-09-12 03:21:59.815852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe69470c54e0'
down_revision = '9e6105d3a34a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_column('owner')

    # ### end Alembic commands ###
